# harvester db
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-harvester-db
type: Opaque
data:
  root_password: {{ .Values.harvester.database.admin_password | b64enc }}
  {{- if .Values.harvester.database.name }}
  database_name: {{ .Values.harvester.database.name | b64enc }}
  {{- end }}
  user_name: {{ .Values.harvester.database.user | b64enc }}
  user_password: {{ .Values.harvester.database.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-harvester-db-id-rsa
type: Opaque
data:
  id_rsa: |-
    {{ $.Files.Get "files/harvester_db_conf/id_rsa" | b64enc }}
