{{- if .Values.harvester.enabled }}
# harvester configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-harvester-envs
type: Opaque
stringData:
  MARIADB_DATABASE: {{ .Values.harvester.database.name | default "harvester" }}
  MARIADB_USER: {{ .Values.harvester.database.user | default "harvester" }}
  MARIADB_PASSWORD: "{{ .Values.harvester.database.password }}"
  MARIADB_ROOT_PASSWORD: "{{ .Values.harvester.database.password }}-admin"
  HARVESTER_DB_HOST: "{{ .Values.harvester.database.dbhost | default (printf "%s-mariadb" (include "harvester_ref" .)) }}"
  {{- if .Values.harvester.database.dbhost_add_index }}
  HARVESTER_DB_HOST_ADD_INDEX: "{{ .Values.harvester.database.dbhost_add_index }}"
  {{- end }}

  PANDA_AUTH_ID_TOKEN: {{ .Values.auth.authIdToken }}
  PANDA_AUTH_VO: {{ .Values.auth.authVO }}
  PANDA_BEHIND_REAL_LB: "1"
  PANDA_VERIFY_HOST: "off"
  PANDA_URL: "https://{{ include "panda_ref" . }}-server:{{ .Values.panda.port }}/server/panda"
  PANDA_URL_SSL: "https://{{ include "panda_ref" . }}-server:{{ .Values.panda.sslPort }}/server/panda"

  BIGMON_BASE_URL: ".Values.bigmon.base_url"

  {{- if .Values.harvester.experiment }}
  EXPERIMENT: {{ .Values.harvester.experiment }}
  {{- end}}

  HARVESTER_ID: "{{ .Values.harvester.harvesterID }}"
  CONDOR_CHANNEL: ".{{ .Values.harvester.condorChannel }}"

  {{- if .Values.cric.real }}
  HARVESTER_CRIC_OS: "{{ .Values.cric.objectStores }}"
  HARVESTER_CRIC_DDMENDPOINTS: "{{ .Values.cric.ddmEndpoints }}"
  HARVESTER_CRIC_URL_DDMENDPOINTS: "{{ .Values.cric.ddmEndpoints }}"
  HARVESTER_CRIC_SCHEDCONFIG: "{{ .Values.cric.schedConfig }}"
  {{- else }}
  HARVESTER_CRIC_OS: "https://{{ include "panda_ref" . }}-server:{{ .Values.panda.sslPort }}/cric/ddm_objectstores.json"
  HARVESTER_CRIC_DDMENDPOINTS: "https://{{ include "panda_ref" . }}-server:{{ .Values.panda.sslPort }}/cric/ddm_endpoints.json"
  HARVESTER_CRIC_URL_DDMENDPOINTS: "https://{{ .Values.panda.hostName }}/cric/ddm_endpoints.json"
  HARVESTER_CRIC_SCHEDCONFIG: "https://{{ include "panda_ref" . }}-server:{{ .Values.panda.ssLPort }}/cric/panda_queues.json"
  {{- end }}

  {{ include "set_proxy" . | indent 2 }}

---
# auth files, for example for google cloud
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-harvester-auth
type: Opaque
data:
  {{- range $path, $_ := .Files.Glob "files/harvester_auth/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

{{- end }}
