# mariadb secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-iam-db
type: Opaque
data:
  root_password: {{ .Values.iam.database.root_password | b64enc }}
  database_name: {{ .Values.iam.database.name | b64enc }}
  user_name: {{ .Values.iam.database.user | b64enc }}
  user_password: {{ .Values.iam.database.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-iam-db-id-rsa
type: Opaque
data:
  id_rsa: |-
    {{ $.Files.Get "files/iam_db_conf/id_rsa" | b64enc }}
