{{- if .Values.panda.enabled }}
# panda configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-panda-envs
type: Opaque
stringData:
  PANDA_DB_PASSWORD: {{ .Values.panda.database.password }}
  PANDA_DB_HOST: "{{ .Values.panda.database.dbhost | default (printf "%s-postgres" (include "panda_ref" .)) }}"
  PANDA_DB_PORT: "{{ .Values.panda.database.dbport }}"
  PANDA_DB_USER: "{{ .Values.panda.database.user | default "panda" }}"
  PANDA_DB_NAME: "{{ .Values.panda.database.name | default "panda_db" }}"

  PANDA_URL: "https://{{ include "panda_ref" . }}-server:{{ .Values.panda.port }}/server/panda"
  PANDA_URL_SSL: "https://{{ include "panda_ref" . }}-server:{{ .Values.panda.sslPort }}/server/panda"
  PANDA_VERIFY_HOST: "off"
  PANDA_AUTH: "oidc"
  PANDA_AUTH_ID_TOKEN: {{ .Values.auth.authIdToken }}
  PANDA_AUTH_VO: {{ .Values.auth.authVO }}

  {{- if .Values.panda.hostName }}
  PANDA_HOSTNAME: "{{ .Values.panda.hostName }}"
  {{- end }}

  # ActiveMQ
  PANDA_ACTIVEMQ_LIST: "{{ include "msgsvc_ref" . }}-activemq:61613"
  PANDA_ACTIVEMQ_PASSWD_panda: {{ .Values.msgsvc.basePasswd }}_panda
  PANDA_ACTIVEMQ_PASSWD_jedi: {{ .Values.msgsvc.basePasswd }}_jedi

  # iDDS
  PANDA_IDDS_HOST: "{{ include "idds_ref" . }}-rest"
  PANDA_IDDS_PORT: "{{ .Values.idds.restPort }}"
  PANDA_IDDS_AUTH_ID_TOKEN: "{{ .Values.auth.authIdToken }}"
  PANDA_IDDS_AUTH_VO: "{{ .Values.auth.authVO }}"
  
  # Rucio
  PANDA_RUCIO_HOST: "{{ .Values.rucio.rucioHost }}"
  PANDA_RUCIO_AUTH_HOST: "{{ .Values.rucio.authHost }}"
  PANDA_RUCIO_USERNAME: "{{ .Values.rucio.username }}"
  PANDA_RUCIO_PASSWORD: "{{ .Values.rucio.password }}"
  PANDA_RUCIO_ACCOUNT: "{{ .Values.rucio.account }}"

  # CRIC
  {{- if .Values.cric.real }}
  PANDA_CRIC_CM: "{{ .Values.cric.costMetrix }}"
  PANDA_CRIC_DDMBLACKLIST: "{{ .Values.cric.ddmBlackList }}"
  PANDA_CRIC_DDMENDPOINTS: "{{ .Values.cric.ddmEndpoints }}"
  PANDA_CRIC_URL_DDMENDPOINTS: "{{ .Values.cric.ddmEndpoints }}"
  PANDA_CRIC_SCHEDCONFIG: "{{ .Values.cric.schedConfig }}"
  PANDA_CRIC_SITES: "{{ .Values.cric.sites }}"
  {{- else }}
  PANDA_CRIC_CM: "/var/cric/cm.json"
  PANDA_CRIC_DDMBLACKLIST: "/var/cric/ddm_blacklist.json"
  PANDA_CRIC_DDMENDPOINTS: "/var/cric/ddm_endpoints.json"
  PANDA_CRIC_URL_DDMENDPOINTS: "http://{{ include "panda_ref" . }}-server:{{ .Values.panda.port }}/cric/ddm_endpoints.json"
  PANDA_CRIC_SCHEDCONFIG: "/var/cric/panda_queues.json"
  PANDA_CRIC_SITES: "/var/cric/sites.json"
  {{- end }}

  # proxy
  {{ include "set_proxy" . | indent 2 }}

---
# certs
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-panda-certs
type: Opaque
data:
  {{- range $path, $_ := .Files.Glob "files/panda_certs/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

---
# auth
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-panda-auth
type: Opaque
stringData:
  {{- range $client := .Values.auth.oidc.clients }}
  {{ $client.name }}_auth_config.json: |-
    {{ $.Files.Get "files/panda_auths/auth_config.json.template" | replace "ROBOT_IDS" $client.robot_ids | replace "ID" $client.client_id | replace "SECRET" $client.client_secret | replace "URL" $.Values.auth.oidc.config_url | replace "AUDIENCE" $.Values.auth.oidc.audience  | replace "NAME" $client.name }}
  {{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-panda-tls-certs
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ $.Files.Get "files/panda_certs/hostcert.pem" | b64enc }}
  tls.key: |-
    {{ $.Files.Get "files/panda_certs/hostkey.pem" | b64enc }}

{{- end }}
