{{- if .Values.ui.enabled }}

# pandaui configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-ui-envs
type: Opaque
stringData:
  # panda-ui
  PANDAUI_NUM_WSGI_PROC: "{{ .Values.ui.numWSGI }}"
  PANDAUI_SECRET_KEY: "{{ .Values.ui.secretKey }}"
  # Auth: IAM only
  AUTH_IAM_ENDPOINT: "{{ .Values.ui.iam.endpoint }}"
  AUTH_IAM_CLIENT_ID: "{{ .Values.ui.iam.client }}"
  AUTH_IAM_CLIENT_SECRET: "{{ .Values.ui.iam.secret }}"
  # DB
  DB_CONN_PANDAUI_VENDOR: "{{ .Values.ui.database.pandaui.vendor }}"
  DB_CONN_PANDAUI_NAME: "{{ .Values.ui.database.pandaui.service }}"
  DB_CONN_PANDAUI_USER: "{{ .Values.ui.database.pandaui.user }}"
  DB_CONN_PANDAUI_PASSWORD: "{{ .Values.ui.database.pandaui.password }}"
  DB_SCHEMA_PANDAUI: "{{ .Values.ui.database.schema.pandaui }}"
  DB_SCHEMA_PANDA: "{{ .Values.ui.database.schema.panda }}"
  # Endpoints of other systems
  PANDA_SERVER_API_URL : "{{ .Values.panda.endpoint.api_url }}"

  {{ include "set_proxy" . | indent 2 }}


# certs
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-ui-certs
type: Opaque
data:
  {{- range $path, $_ := .Files.Glob "files/ui_certs/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-ui-tls-certs
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ $.Files.Get "files/ui_certs/hostcert.pem" | b64enc }}
  tls.key: |-
    {{ $.Files.Get "files/ui_certs/hostkey.pem" | b64enc }}

{{- end }}
