# Default values for harvester - DOMA overrides.
# This is a YAML-formatted file.

harvester:
  experiment: doma

  # DOMA uses static hostPath PVs on node-3
  persistentvolume:
    create: true
    class: manual
    path: "/mnt/harvester-logs"
    selector: false
    size: 50Gi
  persistentvolumewdir:
    selector: false
    size: 50Gi
  persistentvolumecondor:
    create: true
    class: manual
    path: "/mnt/harvester-logs"
    selector: false
    size: 5Gi

  nodeSelector:
    kubernetes.io/hostname: panda-doma-k8s-3bv7ya4fx76z-node-3

  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "4"
      memory: 8Gi

mariadb:
  persistentvolume:
    create: true
    class: manual
    path: "/mnt/harvester-data"
    selector: false
    size: 5Gi

  nodeSelector:
    kubernetes.io/hostname: panda-doma-k8s-3bv7ya4fx76z-node-3

  resources:
    requests:
      cpu: "250m"
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi
