# Default values for harvester - atlas testbed overrides.
# This is a YAML-formatted file.

harvester:
  experiment: atlas
  persistentvolume:
    size: 50Gi
  persistentvolumewdir:
    size: 50Gi
  persistentvolumecondor:
    size: 50Gi
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "4"
      memory: 6Gi

mariadb:
  resources:
    requests:
      cpu: "500m"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi
