# Default values for harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

harvester:
  persistentvolume:
    class: nas
    create: false
    selector: false

  persistentvolumecondor:
    class: nas
    create: false
    selector: false

  experiment: "sphenix"

  noRoot: true

  route:
    enabled: true
    hostName: "FIXME"

mariadb:
  persistentvolume:
    class: nas
    create: false
    selector: false
