# Default values for harvester - atlas testbed overrides.
# This is a YAML-formatted file.

harvester:
  experiment: atlas
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      spec.ingressClassName: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - domain: cern.ch
        hostOverride: bigpanda-tb.cern.ch
        paths:
          - path: /condor_logs
            pathType: Prefix
    tls:
      - hosts:
          - domain: cern.ch
            hostOverride: bigpanda-tb.cern.ch
  persistentvolume:
    create: false
    class: manila-meyrin-cephfs
    selector: false
    size: 50Gi
  persistentvolumewdir:
    size: 50Gi
  persistentvolumecondor:
    create: false
    class: manila-meyrin-cephfs
    selector: false
    size: 50Gi
  resources:
    requests:
      cpu: "2"
      memory: 4Gi
    limits:
      cpu: "6"
      memory: 8Gi

mariadb:
  resources:
    requests:
      cpu: "500m"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi
