# Default values for panda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

server:
  configFile: panda_server_config.atlas_testbed.json
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "4"
      memory: 6Gi
  persistentvolume:
    size: 50Gi
  # use Route class for ingress
  route:
    enabled: false
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    hosts:
      - domain: cern.ch
        hostOverride: pandaserver-tb.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: default
        hosts:
          - domain: cern.ch
            hostOverride: pandaserver-tb.cern.ch

jedi:
  configFile: panda_jedi_config.atlas_testbed.json
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "4"
      memory: 6Gi
  persistentvolume:
    size: 50Gi

postgres:
    enabled: false

    persistentvolume:
      create: false
