# harvester configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harvester.fullname" . }}-configjson
data:
  panda_harvester_configmap.json: |-
{{ .Files.Get "panda_harvester_configmap.json" | indent 4}}
---
# queue config
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harvester.fullname" . }}-queueconfig
data:
{{- (.Files.Glob "queueconfig/*").AsConfig | nindent 2 }}

---
# env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harvester.fullname" . }}-env
data:
  {{- if .Values.httpProxy }}
  http_proxy: "{{ .Values.httpProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }},{{ .Values.panda.host }}"
  {{- else }}
  no_proxy: "localhost,{{ include "harvester.fullname" . }},{{ .Values.panda.host }}"
  {{- end }}
  {{- if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpProxy }}"
  {{- end }}
  {{- else if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpsProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }},{{ .Values.panda.host }},http-{{ .Values.panda.host }}"
  {{- else }}
  no_proxy: "localhost,{{ include "harvester.fullname" . }},{{ .Values.panda.host }},http-{{ .Values.panda.host }}"
  {{- end }}
  {{- end }}

  {{- if .Values.persistentvolumespecial.mount }}
  SPECIAL_MOUNT_POINT: {{ .Values.persistentvolumespecial.path }}
  SPECIAL_LOG_MOUNT_POINT: {{ .Values.persistentvolumespecial.logpath }}
  {{- end }}

---
# sandbox
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harvester.fullname" . }}-sandbox
binaryData:
  {{- range $path, $_ := .Files.Glob "sandbox/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

