mariadb:
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    selector: false
    size: 50Gi

backup:
  persistentvolumespecial:
    mount: true
    class: sdf-data-rubin
    size: 100Gi
