apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: panda-bigmon
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: bigmon=ghcr.io/pandawms/panda-bigmon-core:latest
    argocd-image-updater.argoproj.io/bigmon.update-strategy: digest
    argocd-image-updater.argoproj.io/bigmon.helm.image-name: main.image.repository
    argocd-image-updater.argoproj.io/bigmon.helm.image-tag: main.image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/PanDAWMS/panda-k8s.git
    targetRevision: main
    path: helm/bigmon
    helm:
      valueFiles:
        - values.yaml
        - values/values-atlas_testbed.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
