apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: panda-idds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EdwardKaravakis/panda-k8s.git
    targetRevision: main
    path: helm/idds
    helm:
      valueFiles:
        - values.yaml
        - values-atlas_testbed.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
