apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: panda-image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: panda
      useAnnotations: true
