apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: panda-ui
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/pandawms/panda-ui-backend:latest,frontend=ghcr.io/pandawms/panda-ui-frontend:latest
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/backend.helm.image-name: backend.image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.helm.image-name: frontend.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/PanDAWMS/panda-k8s.git
    targetRevision: main
    path: helm/ui
    helm:
      valueFiles:
        - values.yaml
        - values/values-atlas_testbed.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: panda-ui-backend-sandbox
      jsonPointers:
        - /binaryData
