# Default values for bigmon.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.
#

main:
  tolerations:
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 30
    - key: "node.kubernetes.io/unreachable"
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 30
  persistentvolume:
    create: true
    size: 50Gi

  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        hostOverride: bigpanda-tb.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: "default"
        hosts:
          - domain: cern.ch
            hostOverride: bigpanda-tb.cern.ch
