# Default values for idds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rest:
  replicaCount: 1
  image:
    tag: "2.6.13"
  iddsServer: panda-idds-doma.cern.ch

  persistentvolume:
    create: false
    sharedPvcName: panda-shared-logs
    subPath: idds
  persistentvolumerequests:
    create: false
    sharedPvcName: panda-shared-logs
    subPath: idds-requests
  resources:
    limits:
      cpu: 2000m
      memory: 6Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  serverConf:
    minWorkers: "4"
    maxWorkers: "8"
    numWsgi: "2"
    numWsgiThread: "4"
    maxBacklog: "50"

  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        hostOverride: panda-idds-doma.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: "default"
        hosts:
          - domain: cern.ch
            hostOverride: panda-idds-doma.cern.ch

postgres:
  enabled: false

  resources:
    limits:
      cpu: 2000m
      memory: 8Gi
    requests:
      cpu: 2000m
      memory: 8Gi
