# Default values for messaging service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  secret: "panda-secrets"

activemq:
  # enable 
  enabled: true

  # container image and tag
  image:
    tag: "0.0.4"
    # tag: "main"

  # PV with selector support
  #persistentvolume:
  #    selector: false

  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 4000m
      memory: 16Gi
